#!/bin/sh -e

. /usr/share/debconf/confmodule
test $DEBIAN_SCRIPT_DEBUG && set -v -x


case "$1" in
    install)
    ;;
    upgrade)
    ;;
    configure)
    # Do not do anything. In the past we setup samhain's database but
    # that would send a mail to root on installation and was determined
    # to be unwise (see Debian Bug #749602)
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac


#DEBHELPER#

exit 0
